# Generated by Django 4.0.3 on 2022-11-25 06:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='This field is autogenerated', max_length=100, null=True, unique=True)),
                ('first_reading', models.IntegerField(default=0)),
                ('existing_balance', models.IntegerField(default=100)),
                ('active_phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call Back',
                'verbose_name_plural': 'Mpesa Call Backs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_no', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('organization_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='WaterBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('units', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=145.0, max_digits=9, verbose_name='Unit Price (KES)')),
                ('balance_carried_forward', models.IntegerField(default=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('month', models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=('12', '12'), max_length=10, null=True)),
                ('standing_charge', models.DecimalField(decimal_places=2, default=100, max_digits=9)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client.full_name')),
            ],
            options={
                'verbose_name_plural': 'Water Billing Cycles',
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('metre_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_paid', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.waterbillingcycle')),
            ],
            options={
                'verbose_name': 'Water Billing Payments',
                'verbose_name_plural': 'Water Billing Payments',
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('month', models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=('11', '11'), max_length=10, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.waterbillingcycle', verbose_name='WaterBillingCycle.client')),
            ],
        ),
        migrations.AddField(
            model_name='waterbillingcycle',
            name='meter_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.watermeter'),
        ),
        migrations.AddField(
            model_name='client',
            name='metre_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.watermeter'),
        ),
    ]
