# Generated by Django 4.0.3 on 2022-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_active_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
