# Generated by Django 4.0.3 on 2022-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mpesapayment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='current_reading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='waterconsumption',
            name='previous_reading',
            field=models.IntegerField(),
        ),
    ]
