# Generated by Django 4.0.3 on 2022-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_waterconsumption_current_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='balance_carried_forward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='standing_charge',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=9),
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=9, verbose_name='Unit Price (KES)'),
        ),
    ]
