# Generated by Django 4.0.3 on 2022-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_waterbillingcycle_balance_carried_forward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
    ]
