# Generated by Django 4.0.3 on 2022-11-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_waterbillingcycle_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='standing_charge',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='unit_price',
            field=models.IntegerField(default=120, verbose_name='Unit Price (KES)'),
        ),
    ]
