# Generated by Django 4.0.3 on 2022-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_waterbillingcycle_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.AlterField(
            model_name='waterbillingcycle',
            name='month',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterconsumption',
            name='month',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ManagerClientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('send_to_all', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.ManyToManyField(blank=True, to='core.client')),
            ],
            options={
                'verbose_name_plural': 'Archives | Manager SMS',
            },
        ),
    ]
